version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5454:5454"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    stdin_open: true  # Keep STDIN open for interaction
    tty: true         # Allocate a pseudo-TTY